input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
    target => "app"
    skip_on_invalid_json => true
  }

  if [app][timestamp] {
    date {
      match => ["[app][timestamp]", "ISO8601"]
      target => "@timestamp"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "backend-logs-%{+YYYY.MM.dd}"
  }
}
